### ISSUE TITLE
Zoek online (/libco/search)

### ISSUE THREAD

**Issue by roxannewyns** [libis/Aezel-erfgoed-omeka#30]
Does the WITHIN API support AND and OR search function by now? Or is it still only simple search?

If possible, how much time would it take to extend the search with AND and OR search functions?

**Comment by naeemmuhammad** [comment]
Support for AND and OR operators exists in the current WITH api version (http://api.withculture.eu/assets/developers-lite.html#!/Search/post_api_search2). These operators only work if we add them to the search term in api call. For example "Brussels" AND "Leuven". We will have to add additional control on user interface so that users do not need to type operators along with search terms. It seems to be a work of around two days.

**Comment by roxannewyns** [comment]
geen antwoord meer van partner. voorlopig geen wijzigingen doorvoeren.
